// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs zip-filename-fix`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "zip-viewer",
    "icon": "👁️",
    "name": {
      "en": "ZIP Viewer",
      "ja": "ZIPの中身を確認",
      "zh": "查看 ZIP",
      "de": "ZIP-Viewer",
      "es": "Visor de ZIP"
    },
    "desc": {
      "en": "See what's inside a .zip without extracting it.",
      "ja": "展開せずに.zipの中身を確認します。",
      "zh": "不解压也能看 .zip 里面有什么。",
      "de": "Schau in ein .zip hinein, ohne es zu entpacken.",
      "es": "Ve qué contiene un .zip sin extraerlo."
    }
  },
  {
    "slug": "unzip",
    "icon": "📂",
    "name": {
      "en": "Unzip",
      "ja": "Zip解凍",
      "zh": "解压 ZIP",
      "de": "ZIP entpacken",
      "es": "Descomprimir ZIP"
    },
    "desc": {
      "en": "Extract a .zip and download its files.",
      "ja": ".zip を解凍して中のファイルをダウンロード。",
      "zh": "解压 .zip 并下载其中的文件。",
      "de": "Ein .zip entpacken und die Dateien herunterladen.",
      "es": "Extrae un .zip y descarga sus archivos."
    }
  },
  {
    "slug": "recover-zip",
    "icon": "🩹",
    "name": {
      "en": "Recover ZIP",
      "ja": "壊れたZip救出",
      "zh": "修复 ZIP",
      "de": "ZIP retten",
      "es": "Recuperar ZIP"
    },
    "desc": {
      "en": "Salvage files from a broken or corrupted .zip.",
      "ja": "壊れた/破損した .zip からファイルを救出。",
      "zh": "从损坏的 .zip 中抢救文件。",
      "de": "Dateien aus einem beschädigten .zip retten.",
      "es": "Rescata archivos de un .zip dañado."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'zip-filename-fix';
